
Using cpu device
C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\vec_env\base_vec_env.py:74: UserWarning: The `render_mode` attribute is not defined in your environment. It will be set to None.
  warnings.warn("The `render_mode` attribute is not defined in your environment. It will be set to None.")
Traceback (most recent call last):
  File "train.py", line 52, in <module>
    train()
  File "train.py", line 43, in train
    model.learn(total_timesteps=config.total_timesteps, callback=[checkpoint_callback, wandb_callback])
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\dqn\dqn.py", line 273, in learn
    progress_bar=progress_bar,
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 306, in learn
    progress_bar,
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 289, in _setup_learn
    progress_bar,
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\base_class.py", line 424, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 76, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx])
  File "C:\Users\UFMA\AppData\Roaming\Python\Python37\site-packages\stable_baselines3\common\monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\UFMA\Documents\GitHub\qambo\mundo_fabril\environment.py", line 579, in reset
    super().reset(seed=seed)
TypeError: reset() got an unexpected keyword argument 'seed'